name: GitHub Actions
run-name: GitHub Actions

on:
  push:
    branches:
      '*'
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install cmake
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Archive build
        run: tar -czvf mdTool-macos.tar.gz -C build mdTool
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdTool-macos
          path: mdTool-macos.tar.gz
